### ISSUE TITLE
Long descriptions of grammar points cause cut off text on screen

### ISSUE THREAD

**Issue by AustinSumigray** [esnaultdev/BunPyro#2]
When the grammar point is long past an expected point, it pushes text off the screen. Enclosed is an example.
![Screenshot_20210324-120337_BunPyro](https://user-images.githubusercontent.com/8961217/112344741-cb624780-8c9a-11eb-9771-f735159f3470.jpg)

**Comment by esnaultdev** [comment]
Thank you for the report. It's due to this part of the text being a span. Let me take a look.

**Comment by esnaultdev** [comment]
I forgot to close this issue, but it has been fixed by 32c8751596b99e71143b19a98d62a04c2319515d and dea38caf38bf40af40b923c42af52cdac9a6ee4f. The fix has been released in 0.4.0-alpha02.
