### ISSUE TITLE
Entry of text in review crashes app

### ISSUE THREAD

**Issue by AustinSumigray** [esnaultdev/BunPyro#8]
I have one review at the moment,and any attempt to enter in the correct answer causes the app to crash before I hit any other buttons. I was able to successfully answer the question on the website, but it showed me at -1 reviews. Not sure if related.

**Comment by esnaultdev** [comment]
Thank you for the report, as always. I've just released 0.4.0-alpha04 in Firebase with a fix (c928bc3dba78436dd333007fe509439986e54e09).
Sorry that it impacted your reviews :bowing_man:

> It showed me at -1 reviews. Not sure if related.

I'm still not sure about what could cause this :thinking: The crash should not have had an impact on the data.
I will implement some logging on my side to better understand the issue. For now, I will keep #3 opened to track this.
